### ISSUE TITLE
POSIX properties WebDAV extension

### ISSUE THREAD

**Issue by n-peugnet** [club-1/webdav-server#3]
Create a POSIX properties WebDAV plugin for Sabre/dav that would be able to display POSIX properties.

### Properties to display

1. Uid
2. Gid
3. Mode
4. ... See https://man7.org/linux/man-pages/man2/stat.2.html

### API
This will extends the props of Webdav using Sabre/dav [`afterGetProperty` event](https://sabre.io/dav/1.8/writing-plugins/#%60aftergetproperties%60)

## ToDo

- [ ] define the list of Unix properties to add
- [ ] create the repo and make a basic plugin
- [ ] define the XML schema

Depends on https://github.com/sabre-io/dav/pull/1344
